from __future__ import annotations

from typing import Protocol

from app.domain.entities import Article, Category, ExternalIdentity, RefreshSession, UserPreference


class CategoryRepository(Protocol):
    def list_categories(self) -> list[Category]: ...
    def get_by_slug(self, slug: str) -> Category | None: ...
    def exists_by_slug(self, slug: str) -> bool: ...
    def valid_subcategories(self, category_slug: str) -> set[str]: ...


class ArticleRepository(Protocol):
    def get_by_id(self, article_id: str) -> Article | None: ...
    def list_by_primary(self, category_slug: str) -> list[Article]: ...
    def list_by_primary_and_subcategories(self, category_slug: str, subcategories: list[str]) -> list[Article]: ...
    def list_by_month(self, month: str) -> list[Article]: ...
    def list_by_date(self, archive_date: str) -> list[Article]: ...


class UserPreferenceRepository(Protocol):
    def get(self, user_id: str) -> UserPreference | None: ...
    def save(self, preference: UserPreference) -> UserPreference: ...


class ScrapRepository(Protocol):
    def add(self, user_id: str, article_id: str) -> None: ...
    def remove(self, user_id: str, article_id: str) -> None: ...
    def exists(self, user_id: str, article_id: str) -> bool: ...
    def list_article_ids(self, user_id: str) -> list[str]: ...


class ExternalIdentityRepository(Protocol):
    def get_by_provider_subject(self, provider: str, provider_subject: str) -> ExternalIdentity | None: ...
    def save(self, identity: ExternalIdentity) -> ExternalIdentity: ...


class RefreshSessionRepository(Protocol):
    def get_by_token_hash(self, refresh_token_hash: str) -> RefreshSession | None: ...
    def save(self, session: RefreshSession) -> RefreshSession: ...
    def revoke_by_token_hash(self, refresh_token_hash: str) -> None: ...
